'use client';

import Navbar from '../components/Navbar';
import AuthGuard from '../components/AuthGuard';
import Link from 'next/link';

export default function HelpPage() {
    return (
        <AuthGuard>
            <div className="min-h-screen bg-[#0a0a0f]">
                <Navbar />

                <main className="mx-auto max-w-4xl px-4 pt-24 pb-12 sm:px-6 lg:px-8">
                    {/* Header */}
                    <div className="text-center">
                        <h1 className="text-4xl font-bold tracking-tight text-white sm:text-5xl">
                            How can we <span className="text-transparent bg-clip-text bg-gradient-to-r from-violet-400 to-indigo-500">help you?</span>
                        </h1>
                        <p className="mt-4 text-lg text-zinc-400">
                            Everything you need to know about SecureVault's encrypted storage and security.
                        </p>
                    </div>

                    {/* FAQ Grid */}
                    <div className="mt-16 grid gap-8">
                        <section className="rounded-2xl border border-white/10 bg-white/[0.02] p-8 backdrop-blur-xl">
                            <h2 className="text-xl font-semibold text-white mb-6 flex items-center gap-3">
                                <div className="h-8 w-8 rounded-lg bg-violet-500/10 flex items-center justify-center text-violet-400 text-lg">🔒</div>
                                Security & Encryption
                            </h2>
                            <div className="space-y-6">
                                <div>
                                    <h3 className="text-sm font-medium text-zinc-200">How is my data encrypted?</h3>
                                    <p className="mt-2 text-sm text-zinc-500 leading-relaxed">
                                        SecureVault uses industry-standard AES-256 encryption. Your files are encrypted on the server before being stored, ensuring that even if the storage is compromised, your data remains unreadable without your unique credentials.
                                    </p>
                                </div>
                                <div>
                                    <h3 className="text-sm font-medium text-zinc-200">What is Multi-Factor Authentication (MFA)?</h3>
                                    <p className="mt-2 text-sm text-zinc-500 leading-relaxed">
                                        MFA adds an extra layer of security to your account. Even if someone knows your password, they won't be able to log in without the temporary code generated by your authenticator app (like Google Authenticator or Authy).
                                    </p>
                                </div>
                                <div>
                                    <h3 className="text-sm font-medium text-zinc-200">How do session revocations work?</h3>
                                    <p className="mt-2 text-sm text-zinc-500 leading-relaxed">
                                        You can view all active devices logged into your account in the Security settings. If you see a device you don't recognize, you can "Revoke" that session, which immediately logs that device out and requires a new login.
                                    </p>
                                </div>
                            </div>
                        </section>

                        <section className="rounded-2xl border border-white/10 bg-white/[0.02] p-8 backdrop-blur-xl">
                            <h2 className="text-xl font-semibold text-white mb-6 flex items-center gap-3">
                                <div className="h-8 w-8 rounded-lg bg-indigo-500/10 flex items-center justify-center text-indigo-400 text-lg">📁</div>
                                File Management
                            </h2>
                            <div className="space-y-6">
                                <div>
                                    <h3 className="text-sm font-medium text-zinc-200">What file types can I upload?</h3>
                                    <p className="mt-2 text-sm text-zinc-400">
                                        We support most common file formats including PDF, images (JPG, PNG), documents (DOCX, TXT), and archives (ZIP).
                                    </p>
                                </div>
                                <div>
                                    <h3 className="text-sm font-medium text-zinc-200">I can't see my file list on the Dashboard.</h3>
                                    <p className="mt-2 text-sm text-zinc-400">
                                        The main Dashboard shows a summary of your storage. To see the detailed list of your files, simply click on the <span className="text-violet-400 font-medium">"Total Files"</span> card or head to the <span className="text-indigo-400 font-medium">"Files"</span> option in your profile menu.
                                    </p>
                                </div>
                            </div>
                        </section>

                        <section className="rounded-2xl border border-white/10 bg-[#0f0f17] p-8 text-center">
                            <h2 className="text-lg font-medium text-white">Still have questions?</h2>
                            <p className="mt-2 text-sm text-zinc-500">Our support team is always here to help you secure your digital life.</p>
                            <button className="mt-6 rounded-xl bg-white/5 border border-white/10 px-8 py-3 text-sm font-semibold text-white hover:bg-white/10 transition-all">
                                Contact Support
                            </button>
                        </section>
                    </div>

                    <div className="mt-12 text-center">
                        <Link href="/dashboard" className="text-sm text-zinc-500 hover:text-white transition-colors">
                            ← Back to Dashboard
                        </Link>
                    </div>
                </main>
            </div>
        </AuthGuard>
    );
}
